{% set name = "colcon-mixin" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/colcon-mixin-{{ version }}.tar.gz
  sha256: b65379f5685343cfbd84ce7ae583966523b7b64d786a108dd5843c93092997ae

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - colcon-core >=0.5.6
    - python >=3.6
    - pyyaml

test:
  imports:
    - colcon_mixin
    - colcon_mixin.mixin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://colcon.readthedocs.io
  summary: Extension for colcon to read CLI mixins from files.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - wolfv
    - traversaro
